/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef PARTICLE_RENDER_VS_HPP_
# define PARTICLE_RENDER_VS_HPP_

const char * const particle_render_vs =
  "#version 330 compatibility\n"
  "float x(vec3 m)"
  "{"
    "vec3 f=m+vec3(2.),n=fract(f*f.yzx*222.)+vec3(2.);"
    "f.y*=f.z*n.z;"
    "f.x*=f.y*n.y;"
    "return fract(f.x*f.x);"
  "}"
  "vec3 f(float m)"
  "{"
    "float f=m+2.;"
    "vec3 s=vec3(f,f*f,f*f*f),n=fract(s*222.)+vec3(2.);"
    "return fract(s*n.yzx*n.zxy);"
  "}"
  "float f(float f,float m)"
  "{"
    "return floor(f*m)/m;"
  "}"
  "float f(float f,float m,out float r)"
  "{"
    "float s=f*m,n=floor(s);"
    "r=s-n;"
    "return n/m;"
  "}"
  "float m(float m)"
  "{"
    "return sin(6.28319*m)*.5+.5;"
  "}"
  "float m(vec3 f,float m)"
  "{"
    "vec3 s=f*m,n=floor(s);"
    "float v=x((n+vec3(0.,0.,0.))/m),D=x((n+vec3(1.,0.,0.))/m),g=x((n+vec3(0.,1.,0.))/m),z=x((n+vec3(1.,1.,0.))/m),w=x((n+vec3(0.,0.,1.))/m),y=x((n+vec3(1.,0.,1.))/m),I=x((n+vec3(0.,1.,1.))/m),r=x((n+vec3(1.,1.,1.))/m);"
    "vec3 i=smoothstep(0.,1.,fract(s));"
    "return mix(mix(mix(v,D,i.x),mix(g,z,i.x),i.y),mix(mix(w,y,i.x),mix(I,r,i.x),i.y),i.z);"
  "}"
  "float t(float m)"
  "{"
    "return m/44100;"
  "}"
  "float n(float f)"
  "{"
    "return max(sin(6.28319*(sin(f*.25)+2.)*f),0.);"
  "}"
  "float r(float f)"
  "{"
    "return max(fract(f*2.)*8.-7.,0.);"
  "}"
  "float s(float f)"
  "{"
    "return max(fract(f*2.),0.);"
  "}"
  "float i(float m)"
  "{"
    "return max(sin(6.28319*m*2.)*2.-1.,0.);"
  "}"
  "float v(float m)"
  "{"
    "return max(sin(6.28319*m*2.+3.)*2.-1.,0.);"
  "}"
  "float p(float f)"
  "{"
    "return i(f)+v(f);"
  "}"
  "float w(float m)"
  "{"
    "return max(1.-m*m*.0625,0.);"
  "}"
  "float e(float m)"
  "{"
    "return floor(f(floor(m*12.)/12./60.).x*12.)/12.;"
  "}"
  "float c(float f)"
  "{"
    "return max(fract(f/60.*2.+.75)*4.-3.,0.);"
  "}"
  "float o(float f)"
  "{"
    "return max(fract(f/60.*2.+.25)*4.-3.,0.);"
  "}"
  "float a(float f)"
  "{"
    "return max(fract(f/60.*2.)*4.-3.,0.);"
  "}"
  "float l(float m)"
  "{"
    "return max(sin(12.5664*m/60.)*2.-1.,0.);"
  "}"
  "float g(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708)*2.-1.,0.);"
  "}"
  "float u(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708-1.5708)*2.-1.,0.);"
  "}"
  "float y(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708-1.5708-1.5708)*2.-1.,0.);"
  "}"
  "float z(float m)"
  "{"
    "float f=m-60.;"
    "return max(1.-f*f*.0625,0.);"
  "}"
  "float a(vec3 f,float m)"
  "{"
    "vec3 v=pow(abs(f),vec3(m));"
    "return pow(v.x+v.y+v.z,1/m);"
  "}"
  "float a(vec3 f,float m,float s)"
  "{"
    "return a(f,m)-s;"
  "}"
  "float I(vec3 m)"
  "{"
    "vec3 f=m-vec3(.05);"
    "f=fract(f*12.)-vec3(.5);"
    "return-a(f,4.,.55);"
  "}"
  "vec3 P(vec3 f)"
  "{"
    "float m=.0001;"
    "return normalize(vec3(I(f+vec3(m,0,0))-I(f+vec3(-m,0,0)),I(f+vec3(0,m,0))-I(f+vec3(0,-m,0)),I(f+vec3(0,0,m))-I(f+vec3(0,0,-m))));"
  "}"
  "const mat4x4 D=mat4(-.01/.03,0.,0.,0.,0.,.592593,0.,0.,0.,0.,1.0202,1.,0.,0.,-.02/.99,0.);"
  "uniform float sample_count;"
  "layout(location=0)in vec3 in_position;"
  "layout(location=1)in vec2 in_vert_pos;"
  "void main()"
  "{"
    "float f=t(sample_count);"
    "vec3 m=in_position-vec3(.5,.5,0.);"
    "float s=(g(f)+u(f))*2.*3.14159;"
    "vec2 n=vec2(cos(s),sin(s)),v=n.yx*vec2(-1.,1.);"
    "m.xz=m.x*n+m.z*v-(v*.5-vec2(0.,.5));"
    "m.xy+=in_vert_pos*.004;"
    "gl_Position=D*vec4(m,1.);"
    "if(gl_InstanceID==399998)"
      "gl_Position.xy=in_vert_pos*2.-vec2(1.),gl_Position.y*=1.77778,gl_Position.zw=vec2(.9999,1.);"
    "if(gl_InstanceID==399999)"
      "gl_Position.xy=in_vert_pos*2.-vec2(1.),gl_Position.zw=vec2(.99999,1.);"
    "gl_TexCoord[0].xyz=in_position;"
    "gl_TexCoord[0].w=gl_InstanceID/400000.;"
    "gl_TexCoord[1].xy=in_vert_pos;"
    "gl_TexCoord[1].z=gl_InstanceID==399999?1.:gl_InstanceID==399998?.5:0.;"
  "}";

#endif // PARTICLE_RENDER_VS_HPP_
