/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef PARTICLE_RENDER_FS_HPP_
# define PARTICLE_RENDER_FS_HPP_

const char * const particle_render_fs =
  "#version 330 compatibility\n"
  "float f(vec3 f)"
  "{"
    "vec3 v=f+vec3(2.),m=fract(v*v.yzx*222.)+vec3(2.);"
    "v.y*=v.z*m.z;"
    "v.x*=v.y*m.y;"
    "return fract(v.x*v.x);"
  "}"
  "vec3 x(float f)"
  "{"
    "float m=f+2.;"
    "vec3 v=vec3(m,m*m,m*m*m),r=fract(v*222.)+vec3(2.);"
    "return fract(v*r.yzx*r.zxy);"
  "}"
  "float f(float f,float m)"
  "{"
    "return floor(f*m)/m;"
  "}"
  "float f(float f,float m,out float r)"
  "{"
    "float v=f*m,g=floor(v);"
    "r=v-g;"
    "return g/m;"
  "}"
  "float n(float m)"
  "{"
    "return sin(6.28319*m)*.5+.5;"
  "}"
  "float n(vec3 m,float x)"
  "{"
    "vec3 v=m*x,s=floor(v);"
    "float r=f((s+vec3(0.,0.,0.))/x),g=f((s+vec3(1.,0.,0.))/x),n=f((s+vec3(0.,1.,0.))/x),y=f((s+vec3(1.,1.,0.))/x),l=f((s+vec3(0.,0.,1.))/x),w=f((s+vec3(1.,0.,1.))/x),c=f((s+vec3(0.,1.,1.))/x),o=f((s+vec3(1.,1.,1.))/x);"
    "vec3 p=smoothstep(0.,1.,fract(v));"
    "return mix(mix(mix(r,g,p.x),mix(n,y,p.x),p.y),mix(mix(l,w,p.x),mix(c,o,p.x),p.y),p.z);"
  "}"
  "float m(float m)"
  "{"
    "return m/44100;"
  "}"
  "float t(float f)"
  "{"
    "return max(sin(6.28319*(sin(f*.25)+2.)*f),0.);"
  "}"
  "float s(float f)"
  "{"
    "return max(fract(f*2.)*8.-7.,0.);"
  "}"
  "float v(float f)"
  "{"
    "return max(fract(f*2.),0.);"
  "}"
  "float r(float m)"
  "{"
    "return max(sin(6.28319*m*2.)*2.-1.,0.);"
  "}"
  "float p(float m)"
  "{"
    "return max(sin(6.28319*m*2.+3.)*2.-1.,0.);"
  "}"
  "float w(float f)"
  "{"
    "return r(f)+p(f);"
  "}"
  "float c(float m)"
  "{"
    "return max(1.-m*m*.0625,0.);"
  "}"
  "float h(float f)"
  "{"
    "return floor(x(floor(f*12.)/12./60.).x*12.)/12.;"
  "}"
  "float e(float f)"
  "{"
    "return max(fract(f/60.*2.+.75)*4.-3.,0.);"
  "}"
  "float i(float f)"
  "{"
    "return max(fract(f/60.*2.+.25)*4.-3.,0.);"
  "}"
  "float o(float f)"
  "{"
    "return max(fract(f/60.*2.)*4.-3.,0.);"
  "}"
  "float a(float m)"
  "{"
    "return max(sin(12.5664*m/60.)*2.-1.,0.);"
  "}"
  "float l(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708)*2.-1.,0.);"
  "}"
  "float u(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708-1.5708)*2.-1.,0.);"
  "}"
  "float y(float m)"
  "{"
    "return max(sin(12.5664*m/60.-1.5708-1.5708-1.5708)*2.-1.,0.);"
  "}"
  "float z(float f)"
  "{"
    "float m=f-60.;"
    "return max(1.-m*m*.0625,0.);"
  "}"
  "float a(vec3 f,float m)"
  "{"
    "vec3 v=pow(abs(f),vec3(m));"
    "return pow(v.x+v.y+v.z,1/m);"
  "}"
  "float a(vec3 f,float m,float x)"
  "{"
    "return a(f,m)-x;"
  "}"
  "float g(vec3 f)"
  "{"
    "vec3 m=f-vec3(.05);"
    "m=fract(m*12.)-vec3(.5);"
    "return-a(m,4.,.55);"
  "}"
  "vec3 d(vec3 f)"
  "{"
    "float m=.0001;"
    "return normalize(vec3(g(f+vec3(m,0,0))-g(f+vec3(-m,0,0)),g(f+vec3(0,m,0))-g(f+vec3(0,-m,0)),g(f+vec3(0,0,m))-g(f+vec3(0,0,-m))));"
  "}"
  "uniform float sample_count;"
  "out vec4 color;"
  "vec3 T(float f)"
  "{"
    "vec3 m=fract(f+vec3(0.,2./3.,1./3.));"
    "m=abs(m*2.-1.);"
    "return clamp(m*3.-1.,0.,1.);"
  "}"
  "vec3 C(vec3 f)"
  "{"
    "return((T(f.x)-1.)*f.y+1.)*f.z;"
  "}"
  "vec3 C(float f,float m,float x)"
  "{"
    "return C(vec3(f,m,x));"
  "}"
  "void main()"
  "{"
    "vec3 s=gl_TexCoord[0].xyz;"
    "float x=gl_TexCoord[0].w,r=m(sample_count),p=step(.85,n(vec3(s.xz*.2+vec2(r*.02,0.),0.),200.));"
    "if(x<c(r))"
      "discard;"
    "vec2 g=gl_TexCoord[1].xy;"
    "g=g*2.-vec2(1.,1.);"
    "color=vec4(1.);"
    "if(gl_TexCoord[1].z>.5)"
      "{"
        "float y=g.y*.5+.5+abs(sin(r)*2.)-.6+abs(g.x)*sin(r*1.2+.5)*.5;"
        "color=vec4(.1,.1,.5,1.)+vec4(exp(-y));"
        "color*=.9;"
      "}"
    "else"
      " if(gl_TexCoord[1].z>0.)"
        "{"
          "vec2 y=g+vec2(1.,.5);"
          "float l=atan(y.y,y.x)+r;"
          "const float t=.003;"
          "float a=n(vec3(g,n(r*t)),111.)*.5+n(vec3(g,n(r*t+.1)),222.)*.25+n(vec3(g,n(r*t+.03)),444.)*.125;"
          "if(length(y)+a*.03>(v(r)*.1+.3)*min((r-1.)/8.,1.)&&sin(l*16.)<1.-min((r-20.)/8.,1.))"
            "discard;"
          "color=vec4(C(a*.2/(1.+length(y)*12.),.8,1.),1.);"
        "}"
      "else"
        "{"
          "color=vec4(vec3(1.-s.z+.6),1.);"
          "float y=atan(g.y,g.x)+r*f(vec3(x))*4.,o=sin(y*5.)*.4+.6;"
          "if(length(g)>o)"
            "{"
              "discard;"
            "}"
          "color*=vec4(C(f(vec3(x))*.4,.7,1.)*.5,1.);"
          "float l=s.z-v(r);"
          "l=1.-l*l;"
          "l=pow(l,222.);"
          "color+=vec4(.9)*l;"
        "}"
    "color*=1.-z(r)-pow(c(r),2.);"
  "}";

#endif // PARTICLE_RENDER_FS_HPP_
